### ISSUE TITLE
Stats calculations incorrect

### ISSUE THREAD

**Issue by wingleungchan** [kevinhughes27/parity-server#108]
Still investigating ...

On a throw-drop
- The person who dropped is getting a catch
- The person who threw is getting a completion

On a callahan
- No callahan is being awarded

**Comment by wingleungchan** [comment]
Added callahan code
- normal point is awarded if previous event is PASS and secondActor is goal scorer
- callahan is awarded if previous event is DEFENSE

**Comment by wingleungchan** [comment]
Instead of undoing the previous PASS event, I now check for the next event whenever a PASS is processed to make sure it is not a DROP

**Comment by wingleungchan** [comment]
Also fixed threw-drop calculation.

**Comment by kevinhughes27** [comment]
💖
