### ISSUE TITLE
Raw Stats view salary and calculation.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#111]
Currently the Raw Stats view displays salary as what appears to be: 50k + salary per point played in the game.

It may be better (and more fun) to show salary calculated for the game, and move salary per point played to team view/trade simulator, where it matters (assuming teams will balance against on field contribution and not total salary).

**Comment by kevinhughes27** [comment]
This was my intention with `Pay` but I had a typo in the serialization fixed in https://github.com/kevinhughes27/parity-server/commit/0461cf760589d66a309a63d7c34d92d26b82630a
