### ISSUE TITLE
Trade Simulator/Team Dashboard view salaries.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#112]
Trade and Team view salaries calculate salary incorrectly. Example:

Christopher Keates Week 1 in each view is $94,348. By stat-line, salary should be $68,000. 

Salary for this view may want to move to salary per point (raw, e.g. ~$3,000) and move total salary to Raw Stats view, for the purposes of visualizing salary/balancing teams.

**Comment by kevinhughes27** [comment]
I think this is fixed now. Its Salary vs Pay which is a subtle difference (Salary is normalized per point play and pro rated). There was also a typo which was producing the wrong number for pay earlier.
