### ISSUE TITLE
Darryl Payne shows up in every team's Dashboard.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#113]
Player Darryl Payne shows in every team dashboard. Possibly related to player's unusual stat line. This player played a full game, has points recorded, but has a zero in every statistical category.

EDIT: to clarify, the salary pie chart of the dashboard is the only item affected.

**Comment by wingleungchan** [comment]
I think it is an initialization problem in the JS somewhere. Unfortunately, I do not know enough about JS to dig deeper. 
I do not see any anomaly in /weeks/1/ and in /teams/. If I first load the dashboard for Strike, then load Menace, I see both Darryl and Kristyn repeated. If I go to another team then back to Menace, Kristyn is not there, but Darryl still is.

**Comment by kevinhughes27** [comment]
The best way to fix this is to do #53. Especially for the pie chart

**Comment by kevinhughes27** [comment]
Can someone check if this has been fixed? I think the issue was related to not all teams having full rosters of 14.

**Comment by wingleungchan** [comment]
It looks like the issue with Darryl Payne is fixed (ie: the pie chart now shows the correct players). There still appears to be a problem with the pie chart for the team, Last Jedi, where players names are not showing up. Possibly a z-index issue?

**Comment by kevinhughes27** [comment]
cool. I am going to close then since this will be fixed in #53
