### ISSUE TITLE
Spreadsheets menu item.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#114]
This menu item may want to be an on-hover generated list of links to every year's stats spreadsheets.

e.g.:
Spreadsheets >
 - 2015/2016
 - 2016/2017
 - 2017/2018

**Comment by kevinhughes27** [comment]
Also there is no spreadsheet for this year yet so we should do that as well

**Comment by patrickkenzie** [comment]
Added support for this with #237  - it only has this and last year's sheets currently, as those were public google sheets. @keatesc should we make a public copy of the xls files for the previous years, or open them up for sharing? I think not all of them are publicly shared right now.
