### ISSUE TITLE
Podcast menu item.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#115]
Podcast menu item may want to be an on-hover generated list of links to other relevant pod-casts related to league.

e.g.
Podcasts >
 - 2016/2017
 - 2017/2018
 - Justine and Sully's Underground Radio

**Comment by kevinhughes27** [comment]
Instead of on hover I'd rather make a proper page that lists the podcasts. I was initially looking into embedding a soundcloud widget of sorts but didn't find exactly what I wanted. Ideally this pages fetches data from somewhere and doesn't require manual updates

**Comment by keatesc** [comment]
Page of podcasts, with embedded players, comme ca?

https://andrewberkshire.wordpress.com/author/andrewberkshire/

**Comment by kevinhughes27** [comment]
Yeah I wanted a widget that would also handle fetching all the things and all you give it is a soundcloud ID. I found some stuff but try it out.
