### ISSUE TITLE
Point is duplicated 3 times in last game

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/parity-server#131]
@wingleungchan do you remember anything about the point I threw to Katie?

This point is in the uploaded data 3 times identically. I've seen this before from the new android app but I can't see how it would do this. cc @patrickkenzie 

```json
      "events": [
        {
          "firstActor": "Marcus Bordage",
          "secondActor": "Kate Achtell",
          "timestamp": "Nov 13, 2017 10:42:07 PM",
          "type": "PASS"
        },
        {
          "firstActor": "Kate Achtell",
          "secondActor": "Celine Dumais",
          "timestamp": "Nov 13, 2017 10:42:09 PM",
          "type": "PASS"
        },
        {
          "firstActor": "Celine Dumais",
          "secondActor": "Dan Thomson",
          "timestamp": "Nov 13, 2017 10:42:13 PM",
          "type": "PASS"
        },
        {
          "firstActor": "Dan Thomson",
          "secondActor": "Kevin Hughes",
          "timestamp": "Nov 13, 2017 10:42:16 PM",
          "type": "PASS"
        },
        {
          "firstActor": "Kevin Hughes",
          "secondActor": "Kate Achtell",
          "timestamp": "Nov 13, 2017 10:46:29 PM",
          "type": "PASS"
        },
        {
          "firstActor": "Kate Achtell",
          "timestamp": "Nov 13, 2017 10:46:30 PM",
          "type": "POINT"
        }
      ],
```

We should write something to search for duplicates in the current data as well since there might be more.

**Comment by kevinhughes27** [comment]
this is really an issue with https://github.com/kevinhughes27/parity-client I probably should have opened over there

**Comment by keatesc** [comment]
I've found at least one other set of duplicated points in the game data. Game 5 json:

{
          "firstActor": "Jim Robinson", 
          "timestamp": "Nov 13, 2017 7:45:25 PM", 
          "type": "POINT"
}

Problem is more wide spread than a one off. I recommend we leave this item open until all dupes (week 1 and week 2) are identified and removed under this ticket. CC @patrickkenzie @kevinhughes27

**Comment by kevinhughes27** [comment]
closing here, its being tracked in the client repo
