### ISSUE TITLE
All Weeks view creates extra team names

### ISSUE THREAD

**Issue by patrickkenzie** [kevinhughes27/parity-server#133]
When choosing "All" from the weeks dropdown, the player's team history is combined for their team:

A player that played both weeks for the same team has their team set to "Team1Team1", and a player that was traded has "Team2Team1".

This shows up on the main stats view, and all the joined team names show up in the team dashboard.

**Comment by kevinhughes27** [comment]
I think I know why this happens. I'll fix it tonight.
