### ISSUE TITLE
Derived stats

### ISSUE THREAD

**Issue by wingleungchan** [kevinhughes27/parity-server#135]
I was looking at some stats data and was thinking about extending the stats with some derived numbers. Something like:
Offense efficiency - o_points_for / (o_points_for + o_points_against) - ie: the likelihood of a person scoring when starting on O
Defense efficiency - d_points_for / (d_points_for + d_points_against) - ie: the likelihood of a person scoring when starting on D
Overall efficiency - (o_points for + d_points_for) / (o_points_for + o_points_against + d_points_for + d_points_against)

Some interesting things came up
- In Week 1, Sully's O line was 100%.
- In Week 2, some players with low salaries figured high in efficiency. 

Thoughts?

**Comment by kevinhughes27** [comment]
Very cool. I'm down to add these to the stats calculated on the Stats model class. If we serialize them we can add to the spreadsheets right away and the UI when we want to.

**Comment by kevinhughes27** [comment]
cc @keatesc

**Comment by wingleungchan** [comment]
Branched, committed, and added pull request. I am very new to Git / GitHub, so let me know if I did something wrong.

**Comment by kevinhughes27** [comment]
LGTM! sweet new feature 😃
