### ISSUE TITLE
More derived stats

### ISSUE THREAD

**Issue by wingleungchan** [kevinhughes27/parity-server#169]
Some more interesting derived stats ideas:
Striker - highest goals / catches ratio (some dude is 20/40!!!)
Endzone eyes - highest assists / completions ratio (possibly compare with throwaways / throwdrops)
Lazy ass handler - lowest (goals + assists + 1/2 * 2nd assists) / completions (ie: hangs back, takes resets, moves disc around ...)

**Comment by kevinhughes27** [comment]
Great ideas! 

In terms of inclusion in our code I do want to keep master limited to basic derived metrics like we've got now. These would be fun for the public spreadsheets or even on a branch for analysis for a forum post.

**Comment by wingleungchan** [comment]
Agreed. Speaking of spreadsheets - are they auto generated or is someone manually creating them?

**Comment by kevinhughes27** [comment]
There is a script in the spreadsheet that auto-syncs using the API at some frequency (hourly?) @keatesc has been maintaining the spreadsheets this year.

Not sure if we care but way back I had explored treating spreadsheet scripts like production servers and "deploying" them using https://github.com/kevinhughes27/parity-parser/blob/master/bin/deploy_to_google.js. So we could keep the sync script in github if we wanted.

**Comment by kevinhughes27** [comment]
closing in favour of #177
