### ISSUE TITLE
"Add Rostered Player" is unclear

### ISSUE THREAD

**Issue by patrickkenzie** [kevinhughes27/parity-server#213]
Since adding the "Add Rostered Player" button, we've had a bunch of subs entered as rostered players.

The distinction between the buttons for "Add Rostered Player" and "Add Substitute" in the app doesn't seem to be intuitive - we can better explain the options to statkeepers, but that means remembering to pass that info along to any new volunteers. I think the most reliable approach is to adjust the UI so that a new statkeeper has the best chance of choosing the right thing. A few options came to mind:

1. Remove the option
1. Move the button somewhere less enticing (action menu?)
1. Prompt for sub/roster selection as part of the add player process

Option 1 is tempting now that we have a regular Zuluru sync happening, we're less likely to have incorrect rosters. However, it's helpful for statkeepers to be able to temporarily remove late-arriving players to avoid the auto-selection, and add them back in. 
Option 2 would suffice to help with the above, but still requires outside knowledge and would probably result in the original issue of adding real players as subs.
Option 3 would add an extra step for each sub, but I think it would be the most clear to the statkeeper about what's happening.

**Comment by patrickkenzie** [comment]
@keatesc pointed out that we could also automatically detect whether a player is a sub or a roster player to handle re-adding players. This wouldn't allow statkeepers to override incorrect rosters, but would improve the workflow for the vast majority of roster edits.

I'm thinking we should go with that idea for the standard "Add Player" button, and have a menu item for "advanced mode" that would work like Option 3 above. This would account for the case where the statkeeper knows how they should adjust the roster specifically.

**Comment by kevinhughes27** [comment]
I like @keatesc's idea (side note Keates please commit something so that Github will start auto completing your username). I also have my own idea that links it to option 3. What about making `Substitute` a checkbox that is automatically filled in correctly?
