### ISSUE TITLE
New tablets fail to save game files

### ISSUE THREAD

**Issue by patrickkenzie** [kevinhughes27/parity-server#216]
I believe the cause of #215 was that the game file backup failed to save on the new tablets. We should update the file saving to work for both the old and the new, ideally.

**Comment by kevinhughes27** [comment]
Android changed how permissions work in newer versions which I bet is the cause.

**Comment by patrickkenzie** [comment]
Good call - external storage permission was disabled. Enabling that on the tablets fixed this for now - we'll have to add in explicit permission requests: #220.
