### ISSUE TITLE
Salary cap UI updates

### ISSUE THREAD

**Issue by patrickkenzie** [kevinhughes27/parity-server#228]
The trade simulator page gets used a lot to check for cap compliance. It would be helpful to explicitly show the teams' cap space as a number, to make GMs' lives easier.

@keatesc

**Comment by patrickkenzie** [comment]
We can also add a different warning colour for teams that are under the floor as opposed to over the cap.

@kevinhughes27 do you remember where you got the current colour schemes?

**Comment by kevinhughes27** [comment]
Materializecss has a colors section which I'm pretty sure is where I got them

**Comment by patrickkenzie** [comment]
Also displaying the salary delta for the trades might be nice when there are multiple trades in the works.

**Comment by kevinhughes27** [comment]
UI has changed a fair bit since this was opened.
