### ISSUE TITLE
Setup on Windows

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/parity-server#28]
I'd like to go through getting this app running in windows for curiosity (and ease of future contributors) sake. I'll use the opportunity to check out the latest visual studio code as well.

expected output: updates to the readme

**Comment by briankells** [comment]
npm stalled when trying to install the client. It wouldn't get the meta data for react-router. I researched this issue, and then tried to install the client using yarn instead, which also required that I use "choclatey", a package manager for windows.

Using yarn the client completed its install without issue and I was able to npm run client

**Comment by kevinhughes27** [comment]
Nice! I haven't started using yarn yet but it sounds like that is the way things are going.

**Comment by briankells** [comment]
Server seems to run fine, same with the client.

Trying to use `npm run db:seed` to create the data produces this error. Each attempt to post the json object fails and it tries to move onto the next one.

> seeding with: test/files/week1_game1.json
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' }

**Comment by briankells** [comment]
I've got it up and running fine. All this issue appears to be a result of not having MongoDB up and running properly. Now that I do, I've got the server and client running fine on my machine.

**Comment by kevinhughes27** [comment]
Nice!

![jon stewart excited](https://cloud.githubusercontent.com/assets/1965489/21485993/2ff8363c-cb7a-11e6-8eba-f5e0d1c5a0a2.gif)

Can you open an issue about ensuring some kind of actually useful error is thrown if the server can't connect to the database

**Comment by briankells** [comment]
Good idea

**Comment by kevinhughes27** [comment]
I am closing because of the python re-write. I'll add any required documentation as it comes up.
