### ISSUE TITLE
Provide league configuration data from server

### ISSUE THREAD

**Issue by patrickkenzie** [kevinhughes27/parity-server#371]
It might be useful to include the gender ratio as part of the league data sent to the tablets, to avoid having to update the client app if the player count is changed league to league. This would also simplify things like the tournaments which are not necessarily the same ratio.

**Comment by kevinhughes27** [comment]
closed:
52fa1224231690e8d990aaea0fccfd713b99e648
8d32eef204c9c42fb038057596f713eb6d82b262
d87bd118a15e0a4136a3dc2e6256ee907f3f9a1a
