### ISSUE TITLE
[IDEA] Salary Per Point average

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#56]
Weekly salary increase is a very rough approximation and creates a lot of salary noise. e.g. Nick Therieult, Maya Popovich, week 2 based on very high, possibly unsustainable performance). Team salary and the cap/floor gap can be very sensitive to minor inefficiencies.

Weekly salary increase should be revisited to reflect likely performance given the game. I'm recommending Salary Per Point average(SPPavg)/avg number of points played for an absent game, and that it be retroactive. Absent game salary increase will "adjust" over the season to accurately reflect their performance as SPPavg becomes more and more descriptive of a player.

**Comment by kevinhughes27** [comment]
This is how it works now!
