### ISSUE TITLE
Weekly stats view - show salary increase.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#57]
Salary column for week view should reflect weekly increase, not total salary.

**Comment by kevinhughes27** [comment]
There is the SalaryDelta column for that.

**Comment by keatesc** [comment]
I don't see the column on the server. Presumably not enabled?

**Comment by kevinhughes27** [comment]
Yeah its just not in the UI but its in the db. I whitelist what stats to show here: https://github.com/kevinhughes27/parity-server/blob/master/client/src/Stats.js#L8

**Comment by kevinhughes27** [comment]
you can see raw data by going to `/weeks/1`

**Comment by keatesc** [comment]
Can white listing easily be done by view? Week 1/2/3 etc view could have SalaryDelta, Totals shows total?

**Comment by kevinhughes27** [comment]
Yeah for sure. Its a constant right now but if we make it dynamic and pass it down then everything else just works ™️
