### ISSUE TITLE
Stocki salary increase week 5

### ISSUE THREAD

**Issue by briankells** [kevinhughes27/parity-server#71]
I know Owen's team had some weird issue with missing players from the app this week. How was this resolved?

**Comment by keatesc** [comment]
That's something approximate to his 3 games of performance, averaged over 5 games. He's earned 22k in salary in 3 games of play.

Inflate him to league average and he becomes an overvalued commodity on Owen's team. 1 week's average is about twice what he has provided in on-field value over 3 weeks of play. At the moment he appears to be exactly his value.

**Comment by kevinhughes27** [comment]
Owen's roster didn't update before the game. I fixed the roster here 9812829404836a3a5ad309c7846bd30f29931d41
