### ISSUE TITLE
Trade view issues

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#72]
It looks like when the trade view re-posts after an update to team salaries that team rosters do not re-position correctly relative to their labels.

![image](https://cloud.githubusercontent.com/assets/23219570/20975010/1453a67c-bc6c-11e6-98e9-698791b552a4.png)

**Comment by kevinhughes27** [comment]
> re-posts

what do you mean by this? Do you mean when you click the trade button? (Its all local state on the page there is no post)

> do not re-position correctly relative to their labels.
  
I am un-clear on this point

**Comment by keatesc** [comment]
Re-creating this bug is actually pretty specific. My name/the roster of Kaboom are above "Mike and the Milburys".

On first page load of the trade simulator, default trade of Ben Piper, Trevor Ryan, and the screen looks like this:

![image](https://cloud.githubusercontent.com/assets/23219570/20980715/a7548848-bc7f-11e6-82b2-6ddb173ec6b6.png)

If I click the first text entry area, type "ariel", press down arrow to select Ariel, tab to switch text areas, type "mike", press down arrow to select Mike, press tab and then click on the Trade button, I generate the screenshot seen in the first post.

Once I've done this, if I keep clicking "trade" I am able to generate the following screen...

![image](https://cloud.githubusercontent.com/assets/23219570/20980868/4c25ff8c-bc80-11e6-82c2-0b0d864ed218.png)

**Comment by kevinhughes27** [comment]
Yeah it just keeps swapping the players back between the teams. I looked into reseting the *form* but didn't put it in for v1. Is that basically the issue?

**Comment by keatesc** [comment]
From my last comment on this issue:

 Image 1, Christopher Keates on team Kaboom, team label is Kaboom (correct label).

Image 2, Jamie Wildgen on team Kaboom, team label is Mike and the Milburys (incorrect label).

Performing the trade per the steps I describe causes the team labels to re-sort and render out of order.

**Comment by kevinhughes27** [comment]
Oooooh got it 👍

**Comment by kevinhughes27** [comment]
Its a simple fix - I will just always sort the teams alphabetically before displaying them. Right now it just consumes them in the order they are present in the stats which is non-deterministic. Only some trades would affect this.
