### ISSUE TITLE
Nick Theriault's stats.

### ISSUE THREAD

**Issue by keatesc** [kevinhughes27/parity-server#74]
![image](https://cloud.githubusercontent.com/assets/23219570/21167031/9929272c-c177-11e6-93fb-f02abeac2685.png)

Any idea what's going on? Looks like he has no team (or is now on Team 3), which has shifted his stats to the left.

**Comment by kevinhughes27** [comment]
I've seen this before when there is missing data (its just how the grid component behaves). Its probably fixable I just haven't looked into it.
