### ISSUE TITLE
Return error if the server can't connect to MongoDB

### ISSUE THREAD

**Issue by briankells** [kevinhughes27/parity-server#79]
The server should return a more descriptive error if it fails to connect to the database

**Comment by kevinhughes27** [comment]
Here is an example of where a db connection is established: https://github.com/kevinhughes27/parity-server/blob/master/routes/games.js#L7

the library being used is [monk](https://www.npmjs.com/package/monk).

Our usage looks inline with the documentation so I am not sure what the answer is. At least we have this issue to document that missing mongo might crash in unexpected ways.

**Comment by kevinhughes27** [comment]
closed by python re-write
