### ISSUE TITLE
Complete the test suite

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/parity-server#97]
I implemented the calculation in https://github.com/kevinhughes27/parity-server/pull/96 but didn't complete the test suite. I did get it started though: https://github.com/kevinhughes27/parity-server/blob/master/test.py

For reference this is what I had before: https://github.com/kevinhughes27/parity-server/blob/master/node_server/test/lib/calc_stats_test.js. The inputs will need to be update to match how the new event model looks. I commited an example here: https://github.com/kevinhughes27/parity-server/blob/master/data/ocua_17-18_test.json Note that the points field is actually a json string inside a json object. I'll try and get that fixed up from the android app shortly.

cc @wingleungchan

**Comment by wingleungchan** [comment]
Are you saying that the JSON format is changing as well or would any set of last year's data files should still work with our recode? @kevinhughes27

**Comment by kevinhughes27** [comment]
I am planning to update the json format a bit. Here is what I was thinking:

```json
{
  "league": "ocua_17-18",
  "week": 1,
  "homeTeam": "Team A",
  "awayTeam": "Team A",
  "homeScore": "15",
  "awayScore": "10",
  "homeRoster": ["player1", "player2"],
  "awayRoster": ["player3", "player4"],
  "points": [
     {"offensePlayers": [], "defensePlayers": [], "events": [] }
  ]
}
```

We should update the `Game` model to match the posted JSON.

I might even get as far as using IDs instead of strings for teams and players (cc @patrickkenzie)

**Comment by wingleungchan** [comment]
Thinking about the test cases some more ... for each scenario, should we also test the negative cases? For example, in addition to checking that one person is recorded has having pulls=1, should we also check that everyone else has pulls=0? It ends up making the test case bigger, but it is pretty much a pile of copy / paste. Thoughts?

**Comment by kevinhughes27** [comment]
I think a minimal happy path check is good enough

**Comment by wingleungchan** [comment]
I think I am done with tests now. Let me know if there are other scenarios to test. I will also think of some more.

**Comment by kevinhughes27** [comment]
I quickly looked through the commits - looks great! I must not have re-built the app after fixing the home and away roster bug. The test data @patrickkenzie uploaded looks fine though so it is fixed. Thanks for cleaning up the data.
